sequenceDiagram
    participant Client
    participant WebServer as Web Server
    participant index.php
    activate WebServer
    Client->>WebServer: HTTP Request
    WebServer->>index.php: Passes HTTP Request
    activate index.php
    index.php->>index.php: execute
    index.php->>WebServer: HTTP Response
    deactivate index.php
    WebServer->>Client: HTTP Response
