sequenceDiagram
  participant Client
  participant Server as New Laravel Application Instance
  participant Event
  participant Listener
  Client->>Server: HTTP request
  activate Server
  Server->>Event: Dispatch event
  Event->>Listener: Event is listened to synchronously
  Listener-->>Server: Listener handles event
  Server-->>Client: Return response
  deactivate Server
