
graph RL;
  Browser1(Browser Client 1) <--> |HTTP Request/Reponse|HttpdModule;
  Browser2(Browser Client 2) --> |HTTP Request|HttpdModule;
  subgraph OS[OS]
    style OS fill:#ffffff00,stroke:#333;
    subgraph Apache["Apache HTTP Server (Master Process)"]
        HttpdModule["httpd Apache Listener<br>(functionality)"] -->|Forwards Request| Queue;
        MP((("Apache HTTP Server (Master Process)"))) -->|use|MPM;
        MP --> |monitor|Pool;
        MP --> |start|HttpdModule;
        MPM --> |to create|Pool;
        style Apache fill:#f9f9f9,stroke:#333;
        Queue[[Request Queue]];
        MPM{{"`Multi-Processing Module (**mpm_prefork**)`"}}
        subgraph Pool[Pool]
            direction TB;
            style Pool fill:#f9f9f9,stroke:#333;
            Worker1("Worker 1 (Process)");
            Worker2("Worker 2 (Process)");
            Worker3("Worker 3 (Process)");
        end
        Pool -. "watches" .-> Queue;
    end
    Worker1 -->|Access| FileSystem[File System];
    Worker1 -->|Forwards Generated Response|HttpdModule;
    Worker2 -->|Access| FileSystem;
    Worker3 -->|Access| FileSystem;
    FileSystem -->|Retrieve| WelcomePage[public/welcome.html];
    subgraph SourceCode[Application Source Code]
        style SourceCode fill:#f9f9f9,stroke:#333;
        WelcomePage[public/welcome.html];
    end
  end
  style HttpdModule fill:#85C1E9,stroke:#333;
  style Queue fill:#F7DC6F,stroke:#333;
  style Worker1 fill:#82E0CA,stroke:#333;
  style Worker2 fill:#82E0CA,stroke:#333;
  style Worker3 fill:#82E0CA,stroke:#333;
  style FileSystem fill:#E59866,stroke:#333;
  style SourceCode fill:#E59866,stroke:#333;
  style MP fill:#82E0AA,stroke:#333;
  linkStyle 0,2,7,9 stroke: red;
