sequenceDiagram
  participant C as Client
  participant WS as WebSocket Server
  participant L as Laravel Application
  C->>L: HTTP request
  L-->>C: HTTP response (HTML, CSS, JS)
  Note over C: JS received knows how to reach the Websocket Server
  C->>WS: Establish WebSocket connection
  L->>WS: Broadcast event on update
  WS-->>C: Push update to client
  Note over C: JS received knows how to listen to the Websocket Server
  C->>C: Update page
