sequenceDiagram
    participant Client
    participant WebServer as Web Server
    participant index.php
    Client->>WebServer: HTTP Request
    WebServer->>index.php: Passes HTTP Request
    activate index.php
    index.php->>index.php: Define LARAVEL_START
    index.php->>index.php: Check If The Application Is Under Maintenance
    index.php->>index.php: Register The Auto Loader
    index.php->>index.php: Run The Application
    index.php->>WebServer: HTTP Response
    index.php->>index.php: Terminate The Application
    deactivate index.php
    WebServer->>Client: HTTP Response
