
graph RL;
  Browser1(Browser Client 1) <--> |HTTP Request/Reponse|HttpdModule;
  Browser2(Browser Client 2) --> |HTTP Request|HttpdModule;
  subgraph OS[OS]
    style OS fill:#ffffff00,stroke:#333;
    subgraph Apache["Apache HTTP Server (Master Process)"]
        HttpdModule["httpd Apache Listener<br>(functionality)"] -->|Forwards Request| Queue;
        MP((("Apache HTTP Server (Master Process)"))) -->|use|MPM;
        MP --> |monitor|Pool;
        MP --> |start|HttpdModule;
        MPM --> |to create|Pool;
        style Apache fill:#f9f9f9,stroke:#333;
        Queue[[Request Queue]];
        MPM{{"`Multi-Processing Module (**mpm_worker**)`"}}
        MODP{{"mod_cgi"}}
        MP --> |loads at start|MODP
        subgraph Pool[Pool]
            direction TB;
            style Pool fill:#f9f9f9,stroke:#333;

            subgraph Worker1["Worker 1 (Process)"];
                Thread1_1("Thread 1");
                Thread1_2("Thread 2");
            end       

            subgraph Worker2["Worker 2 (Process)"];
                Thread2_1("Thread 1");
                Thread2_2("Thread 2");
            end       

            subgraph Worker3["Worker 3 (Process)"];
                Thread3_1("Thread 1");
                Thread3_2("Thread 2");
            end       
        end

        subgraph CGI_Process["CGI Process"]
            PI("PHP Interpreter");
        end

        Pool -. "watches" .-> Queue;

        Thread1_1 -->|starts child process|CGI_Process;
        Thread1_1 -->|passes HTTP Request|CGI_Process;
        CGI_Process --> |sends Generated HTTP Response|Thread1_1;
        Thread1_1 --> |terminates|CGI_Process;

    end
    Thread1_1 -->|Access| FileSystem[File System];
    Thread1_1 -->|Forwards Generated Response|HttpdModule;
    FileSystem -->|Retrieve| WelcomePage[public/index.php];
    subgraph SourceCode[Application Source Code]
        style SourceCode fill:#f9f9f9,stroke:#333;
        WelcomePage[public/index.php];
    end
  end
  style HttpdModule fill:#85C1E9,stroke:#333;
  style Queue fill:#F7DC6F,stroke:#333;
  style Worker1 fill:#82E0CA,stroke:#333;
  style Worker2 fill:#82E0CA,stroke:#333;
  style Worker3 fill:#82E0CA,stroke:#333;
  style FileSystem fill:#E59866,stroke:#333;
  style SourceCode fill:#E59866,stroke:#333;
  style MP fill:#82E0AA,stroke:#333;
  linkStyle 0,2,8,10,11,14 stroke: red;
