graph TB
  IP["IP Protocol (Network Layer)"]
  IP --> TCP["TCP Protocol (Transport Layer)"]
  TCP --> HTTP["HTTP Protocol (Application Layer)"]
  TCP --> WS["WebSocket Protocol (Application Layer)"]
  IP --> UDP["UDP Protocol (Transport Layer)"]
  UDP --> WRTC["WebRTC Protocol (Application Layer)"]
